name: PROMINENCE
title: PROMINENCE
description: Enabling HTC & HPC applications opportunistically across private, academic and public clouds
repository: "prominence-eosc/docs"
remote_theme: just-the-docs/just-the-docs
url: "https://prominence-eosc.github.io"
baseurl: "/docs"

plugins:
  - jekyll-include-cache

